package org.example.lexer;

public enum TokenType {
    EOF, ERROR,
    L_PAREN, R_PAREN, L_BRACE, R_BRACE, L_BRACKET, R_BRACKET,
    COMMA, DOT, COLON, BEER,
    PLUS, MINUS, STAR, SLASH, PERCENT,
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    AND_AND, OR_OR,
    IDENTIFIER, INT_LITERAL, FLOAT_LITERAL, BOOL_LITERAL, STRING_LITERAL,
    CASA, LIMENKA, KRIGLA, BOMBA, PINTA, PIJAN, CHAR,
    IF, ELSE, WHILE, RETURN, FN,
    READ, PRINT
}
